backend:
  name: github
  repo: Risevista/risevista
  branch: main
  base_url: https://risevista.pages.dev/
  auth_endpoint: /api/auth
  site_domain: risevista.pages.dev

locale: "ja"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日", name: "date", widget: "datetime", required: true }
      - { label: "本文", name: "body", widget: "markdown", required: true }
  
  - name: "properties"
    label: "取り扱い物件"
    folder: "src/content/properties"
    create: true
    slug: "{{slug}}"
    extension: "md"
    preview_path: "properties/{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string", required: true }
      - { label: "公開日", name: "date", widget: "datetime", required: true }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image", required: true }
      - { label: "外部リンク", name: "link", widget: "string", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: false }
