backend:
  name: github
  repo: Risevista/HP        # ← GitHub org/リポジトリ名に変更
  branch: main              # ← デフォルトブランチに合わせて（main / master / production）
  site_domain: risevista.pages.dev
  base_url: https://risevista.pages.dev/
  auth_endpoint: auth

locale: "ja"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
